// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YnclinoAMS.Data;

#nullable disable

namespace YnclinoAMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603110000_AddTenantDateOfBirth")]
    partial class AddTenantDateOfBirth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("YnclinoAMS.Models.tblUser", b =>
            {
                b.Property<int>("UserID").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("Password").IsRequired().HasMaxLength(255).HasColumnType("TEXT");
                b.Property<string>("Role").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER");
                b.Property<bool>("IsSuperAdmin").HasColumnType("INTEGER");
                b.Property<DateTime>("DateCreated").HasColumnType("TEXT");
                b.HasKey("UserID");
                b.HasIndex("Username").IsUnique();
                b.ToTable("tblUsers");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblUnit", b =>
            {
                b.Property<int>("UnitID").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("UnitNumber").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("UnitType").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<decimal>("RentPrice").HasColumnType("TEXT");
                b.Property<int>("Capacity").HasColumnType("INTEGER");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT").HasDefaultValue("Vacant");
                b.Property<DateTime>("DateAdded").HasColumnType("TEXT");
                b.HasKey("UnitID");
                b.HasIndex("UnitNumber").IsUnique();
                b.ToTable("tblUnits");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblTenant", b =>
            {
                b.Property<int>("TenantID").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int?>("UserID").HasColumnType("INTEGER");
                b.Property<int>("UnitID").HasColumnType("INTEGER");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("LastName").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("ContactNumber").HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("EmergencyContact").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<DateTime?>("DateOfBirth").HasColumnType("TEXT");
                b.Property<DateTime?>("MoveInDate").HasColumnType("TEXT");
                b.Property<DateTime?>("MoveOutDate").HasColumnType("TEXT");
                b.Property<DateTime?>("LeaseStart").HasColumnType("TEXT");
                b.Property<DateTime?>("LeaseEnd").HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT").HasDefaultValue("Active");
                b.Property<DateTime>("DateRecorded").HasColumnType("TEXT");
                b.HasKey("TenantID");
                b.HasIndex("UserID");
                b.HasIndex("UnitID");
                b.ToTable("tblTenants");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblBilling", b =>
            {
                b.Property<int>("BillingID").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("TenantID").HasColumnType("INTEGER");
                b.Property<DateTime>("BillingPeriod").HasColumnType("TEXT");
                b.Property<decimal>("AmountDue").HasColumnType("TEXT");
                b.Property<DateTime>("DueDate").HasColumnType("TEXT");
                b.Property<decimal?>("AmountPaid").HasColumnType("TEXT");
                b.Property<DateTime?>("DatePaid").HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT").HasDefaultValue("Unpaid");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<DateTime>("DateIssued").HasColumnType("TEXT");
                b.HasKey("BillingID");
                b.HasIndex("TenantID");
                b.ToTable("tblBillings");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblMaintenanceRequest", b =>
            {
                b.Property<int>("RequestID").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("TenantID").HasColumnType("INTEGER");
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("Priority").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("TEXT").HasDefaultValue("Pending");
                b.Property<DateTime>("DateSubmitted").HasColumnType("TEXT");
                b.Property<DateTime?>("DateResolved").HasColumnType("TEXT");
                b.Property<string>("AdminNotes").HasMaxLength(500).HasColumnType("TEXT");
                b.HasKey("RequestID");
                b.HasIndex("TenantID");
                b.ToTable("tblMaintenanceRequests");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblLostFoundItem", b =>
            {
                b.Property<int>("ItemID").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("ReportedByUserID").HasColumnType("INTEGER");
                b.Property<string>("ItemName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("ItemType").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.Property<string>("Location").HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT").HasDefaultValue("Reported");
                b.Property<DateTime>("DateReported").HasColumnType("TEXT");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("TEXT");
                b.HasKey("ItemID");
                b.HasIndex("ReportedByUserID");
                b.ToTable("tblLostFoundItems");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblTenant", b =>
            {
                b.HasOne("YnclinoAMS.Models.tblUser", "User").WithMany("Tenants").HasForeignKey("UserID").OnDelete(DeleteBehavior.SetNull);
                b.HasOne("YnclinoAMS.Models.tblUnit", "Unit").WithMany("Tenants").HasForeignKey("UnitID").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("User");
                b.Navigation("Unit");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblBilling", b =>
            {
                b.HasOne("YnclinoAMS.Models.tblTenant", "Tenant").WithMany().HasForeignKey("TenantID").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Tenant");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblMaintenanceRequest", b =>
            {
                b.HasOne("YnclinoAMS.Models.tblTenant", "Tenant").WithMany().HasForeignKey("TenantID").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Tenant");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblLostFoundItem", b =>
            {
                b.HasOne("YnclinoAMS.Models.tblUser", "ReportedBy").WithMany().HasForeignKey("ReportedByUserID").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("ReportedBy");
            });

            modelBuilder.Entity("YnclinoAMS.Models.tblUnit", b => { b.Navigation("Tenants"); });
            modelBuilder.Entity("YnclinoAMS.Models.tblUser", b => { b.Navigation("Tenants"); });
#pragma warning restore 612, 618
        }
    }
}
