// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YnclinoAMS.Data;

#nullable disable

namespace YnclinoAMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603000001_AddBillingMaintenanceLostFound")]
    partial class AddBillingMaintenanceLostFound
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YnclinoAMS.Models.tblBilling", b =>
                {
                    b.Property<int>("BillingID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillingID"));
                    b.Property<decimal>("AmountDue").HasColumnType("decimal(10,2)");
                    b.Property<decimal?>("AmountPaid").HasColumnType("decimal(10,2)");
                    b.Property<DateTime>("BillingPeriod").HasColumnType("datetime2");
                    b.Property<DateTime>("DateIssued").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("GETDATE()");
                    b.Property<DateTime?>("DatePaid").HasColumnType("datetime2");
                    b.Property<DateTime>("DueDate").HasColumnType("datetime2");
                    b.Property<string>("Notes").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Unpaid");
                    b.Property<int>("TenantID").HasColumnType("int");
                    b.HasKey("BillingID");
                    b.HasIndex("TenantID");
                    b.ToTable("tblBillings");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblLostFoundItem", b =>
                {
                    b.Property<int>("ItemID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));
                    b.Property<DateTime>("DateReported").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("GETDATE()");
                    b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("ItemName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("ItemType").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                    b.Property<string>("Location").HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Notes").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<int>("ReportedByUserID").HasColumnType("int");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Reported");
                    b.HasKey("ItemID");
                    b.HasIndex("ReportedByUserID");
                    b.ToTable("tblLostFoundItems");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblMaintenanceRequest", b =>
                {
                    b.Property<int>("RequestID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));
                    b.Property<string>("AdminNotes").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<DateTime>("DateSubmitted").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("GETDATE()");
                    b.Property<DateTime?>("DateResolved").HasColumnType("datetime2");
                    b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("Priority").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(30).HasColumnType("nvarchar(30)").HasDefaultValue("Pending");
                    b.Property<int>("TenantID").HasColumnType("int");
                    b.HasKey("RequestID");
                    b.HasIndex("TenantID");
                    b.ToTable("tblMaintenanceRequests");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblTenant", b =>
                {
                    b.Property<int>("TenantID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantID"));
                    b.Property<string>("ContactNumber").HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<DateTime>("DateRecorded").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("GETDATE()");
                    b.Property<string>("EmergencyContact").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("FirstName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("LastName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<DateTime?>("LeaseEnd").HasColumnType("datetime2");
                    b.Property<DateTime?>("LeaseStart").HasColumnType("datetime2");
                    b.Property<DateTime?>("MoveInDate").HasColumnType("datetime2");
                    b.Property<DateTime?>("MoveOutDate").HasColumnType("datetime2");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Active");
                    b.Property<int>("UnitID").HasColumnType("int");
                    b.Property<int?>("UserID").HasColumnType("int");
                    b.HasKey("TenantID");
                    b.HasIndex("UnitID");
                    b.HasIndex("UserID");
                    b.ToTable("tblTenants");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblUnit", b =>
                {
                    b.Property<int>("UnitID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitID"));
                    b.Property<int>("Capacity").HasColumnType("int");
                    b.Property<DateTime>("DateAdded").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("GETDATE()");
                    b.Property<decimal>("RentPrice").HasColumnType("decimal(10,2)");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Vacant");
                    b.Property<string>("UnitNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("UnitType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.HasKey("UnitID");
                    b.HasIndex("UnitNumber").IsUnique();
                    b.ToTable("tblUnits");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblUser", b =>
                {
                    b.Property<int>("UserID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));
                    b.Property<DateTime>("DateCreated").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("GETDATE()");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<bool>("IsSuperAdmin").HasColumnType("bit");
                    b.Property<string>("Password").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<string>("Role").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.HasKey("UserID");
                    b.HasIndex("Username").IsUnique();
                    b.ToTable("tblUsers");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblBilling", b =>
                {
                    b.HasOne("YnclinoAMS.Models.tblTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblLostFoundItem", b =>
                {
                    b.HasOne("YnclinoAMS.Models.tblUser", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblMaintenanceRequest", b =>
                {
                    b.HasOne("YnclinoAMS.Models.tblTenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblTenant", b =>
                {
                    b.HasOne("YnclinoAMS.Models.tblUnit", "Unit")
                        .WithMany("Tenants")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("YnclinoAMS.Models.tblUser", "User")
                        .WithMany("Tenants")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Unit");
                    b.Navigation("User");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblUnit", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("YnclinoAMS.Models.tblUser", b =>
                {
                    b.Navigation("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
